<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sunilr201-PC" failures="1" tests="1" name="chrometest" time="0.044" errors="0" timestamp="2024-11-29T20:33:36 IST">
  <testcase classname="utilities.DataProviders" name="dataTest" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.NullPointerException">
      <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException
at java.base/java.io.File.<init>(File.java:278)
at utilities.DataProviders.dataSupplier(DataProviders.java:30)
... 19 more
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- dataTest -->
</testsuite> <!-- chrometest -->
